### ISSUE TITLE
Looping on post that are the same day

### ISSUE THREAD

**Issue by twistedatoms** [DelgadoJosh/WanderingInnScraper#12]
I noticed that program is looping on Volume 7 at the end when pirateaba posted all the solstice 1-9. the only think i can think that is different is because a bunch of them have the same posted date? https://wanderinginn.com/2020/12/23/solstice-pt-[1-9]/

let me know what else you might need from me to resolve. Also thank you very much for making this tool

**Comment by DelgadoJosh** [comment]
Thanks for the reach out! Let me take a look. There's a possibility that we may need to update links.json if pirateaba updated the urls.

**Comment by DelgadoJosh** [comment]
Hmm... Interesting, I can't seem to reproduce the issue?

I'm starting from 7.62 and ending on 8.01 and it's downloading them without looping
https://wanderinginn.com/2020/12/13/7-62/
https://wanderinginn.com/2021/01/13/8-01/

![image](https://user-images.githubusercontent.com/34148647/200712757-52977f3b-c6ff-4bfe-9f6c-a21b037c0950.png)


Can you make sure that you downloaded the "links.json" file and have it in the same folder as the executable ("WanderingInnScraperV1.6") or the script?

**Comment by twistedatoms** [comment]
This seems to be an issue on my side I redownloaded the links.json file and it is working now. apologies for the trouble

**Comment by DelgadoJosh** [comment]
No worries! I'm glad it works now! 

I probably should edit the instructions to recommend the links.json if you want to download everything, and to have a fallback hardcoded links.json if it's not downloaded
